site_name: Metrô-DF

theme:
  name: material
  favicon: imagens/logoMetroDF.png
  logo: imagens/logoMetroDF.png
  palette:
    primary: green
  language: pt

docs_dir: docs/

nav: 
  - Sobre o projeto: index.md
  - Planejamento: Planejamento/planejamento.md
  - Pré-rastreabilidade: 
      - Rich Picture: Pre-Rastreabilidade/RichPicture.md


